version: '2'
services:
  app:
    #build:
    #  context: ./
    #  dockerfile: app.dockerfile
    image: python:3.6-alpine
    working_dir: /var/www
    volumes:
      - ../:/var/www
    command: pip install -r requirements.txt
    tty: true
    container_name: 'f_app'

  web:
    build:
      context: ./
      dockerfile: server.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    container_name: 'f_server'
    ports:
      - 8000:80

  database:
    image: daocloud.io/mysql:5.7.4
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - 'MYSQL_USER=cili'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
    container_name: 'f_db'

  redis:
    image: daocloud.io/library/redis:4.0.10-alpine
    command: redis-server --appendonly yes
    container_name: 'l_redis'

volumes:
  dbdata: