version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
    tty: true
    container_name: 'f_app'

  web:
    build:
      context: ./
      dockerfile: server.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    container_name: 'f_server'
    ports:
      - 8000:80

  database:
    image: daocloud.io/mysql:5.7.4
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    container_name: 'f_db'
    ports:
      - '